apiVersion: apps/v1
kind: Deployment
metadata:

spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-tracker
  template:
    metadata:
      labels:
        app: movie-tracker
        app.kubernetes.io/name: movie-tracker
    spec:
      containers:
        - name: movie-tracker
          image: localhost:32000/movie-tracker
          imagePullPolicy: Always
          env:
            - name: 'MONGODB_CONNECTION_STRING'
              value: '...'
          ports:
            - containerPort: 8080
              name: http-web
---
apiVersion: v1
kind: Service
metadata:
  name: movie-tracker-service
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: movie-tracker-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: http-web
